spring:
  datasource:
    url: jdbc:h2:mem:~/langdy?MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        storage_engine: innodb
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        orm:
          jpa: debug
        transaction: debug
